{
 "title": "HLL Serverübersicht",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ping",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "network_ping_avg", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "Packetloss",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "network_packet_loss", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "Jitter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "network_jitter", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "Spieler",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hll_crcon_player_count", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "Netzwerk",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "network_ping_avg", "legendFormat": "ping_avg - {{server_id}}" },
    { "expr": "network_packet_loss", "legendFormat": "packet_loss - {{server_id}}" },
    {
     "expr": "network_traceroute_num_hops",
     "legendFormat": "traceroute_num_hops - {{server_id}}"
    },
    { "expr": "network_jitter", "legendFormat": "jitter - {{server_id}}" }
   ]
  }
 ]
}