{
 "title": "HLL Serverdetails",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": { "query": "label_values(server_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Spieler",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hll_crcon_player_count{server_id=\"$server\"}",
     "legendFormat": "player_count - {{server_id}}"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ping_avg{server_id=\"$server\"}",
     "legendFormat": "ping_avg - {{server_id}}"
    }
   ]
  },
  {
   "title": "Packetloss",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_packet_loss{server_id=\"$server\"}",
     "legendFormat": "packet_loss - {{server_id}}"
    }
   ]
  },
  {
   "title": "Spielzeit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hll_crcon_game_time{server_id=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Netzwerk in Relation zu HLL",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "network_ping_avg{server_id=\"$server\"}",
     "legendFormat": "network_ping_avg"
    },
    {
     "expr": "network_packet_loss{server_id=\"$server\"}",
     "legendFormat": "network_packet_loss"
    },
    {
     "expr": "hll_crcon_player_count{server_id=\"$server\"}",
     "legendFormat": "hll_crcon_player_count"
    },
    {
     "expr": "hll_crcon_game_time{server_id=\"$server\"} / 5400 * 100",
     "legendFormat": "hll_crcon_game_time"
    },
    {
     "expr": "network_traceroute_num_hops{server_id=\"$server\"}",
     "legendFormat": "network_traceroute_num_hops"
    }
   ]
  }
 ]
}